### PR TITLE
mailers

### PR DESCRIPTION
**Pull request by Meeeeeesh**

### CODE REVIEW

**Comment by mcmillanator** [comment]
You've added methods for the session controller and in the application helper.  This makes me think that the session helper is not working.  Should we remove it?

**Comment by Meeeeeesh** [comment]
It works, I just wanted to make sure I could do it as well.

**Comment by rpearce** [comment]
PRs which change 24 files probably shouldn't be merged by the person who made the changes. It's always a good idea to have another set of eyes look at it

**Comment by Meeeeeesh** [comment]
The merge was an honest mistake. Stanley and I discussed this today.

**Comment by mcmillanator** [comment]
We did.  It's all good.  :)

**Pull request merged**
